// Data Set for sidebar
const sideBarHead = [
  "Python Home",
  "Python Intro",
  "Python Getting Started",
  "Python Syntax",
  "Python Component",
  "Python Variable",
  "Python Data Types",
  "Python Numbers",
  "Python Casting",
  "Python Settings",
  "Python Boolean",
  "Python Operators",
  "Python Lists",
  "Python Tuples",
  "Python Sets",
  "Python Dictionaries",
  "Python If....Else",
  "Python While Loops",
  "Python For Loops",
  "Python Functions",
  "Python Lamdba",
  "Python Arrays",
  "Python Classes/Objects",
  "Python Inheritance",
  "Python Iterators",
  "Python Polymorphism",
  "Python Scope",
  "Python Modules",
  "Python Dates",
  "Python JSON",
  "Python RegEx",
  "Python PHP",
  "Python Try...Except",
  "Python User Input",
  "Python String Formatting",
];

const sideBar = document.getElementById("sidebarTarg");
